version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql-usuariosdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: usuariosdb
    ports:
      - "3307:3306"
    networks:
      - usuario-network

  app:
    build: .
    container_name: usuarioapp-spring
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/usuariosdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db
    networks:
      - usuario-network

networks:
  usuario-network:
